import { Directory, File, Paths } from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const exportsDirectory = new Directory(Paths.cache, 'pavo-exports');

/** Writes generated bytes to a temporary file the teacher can print or share. */
export function writeExport(bytes: Uint8Array, fileName: string): File {
  if (!exportsDirectory.exists) exportsDirectory.create({ intermediates: true, idempotent: true });
  const file = new File(exportsDirectory, fileName.replace(/[^A-Za-z0-9._-]/g, '_'));
  file.create({ overwrite: true });
  file.write(bytes);
  return file;
}

export async function printPdf(bytes: Uint8Array, fileName: string): Promise<void> {
  await Print.printAsync({ uri: writeExport(bytes, fileName).uri });
}

export async function sharePdf(bytes: Uint8Array, fileName: string): Promise<void> {
  const file = writeExport(bytes, fileName);
  await Sharing.shareAsync(file.uri, { mimeType: 'application/pdf', dialogTitle: fileName });
}

export async function shareFile(bytes: Uint8Array, fileName: string, mimeType: string): Promise<void> {
  const file = writeExport(bytes, fileName);
  await Sharing.shareAsync(file.uri, { mimeType, dialogTitle: fileName });
}
